swagger: '2.0'
info:
  title: api
  version: '1.0'
host: status.aws.amazon.com
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /data.json:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          schema:
            $ref: ../models/response/dataResponse.v1.yaml
      operationId: get-data.json
      parameters:
        - in: body
          name: body
          schema:
            $ref: ../models/request/dataRequest.v1.yaml
definitions: {}
